export const FETCH_WINE_REVIEWS = 'FETCH_WINE_REVIEWS';
export const FETCH_WINE_REVIEWS_SUCCESS = 'FETCH_WINE_REVIEWS_SUCCESS';
export const FETCH_WINE_REVIEWS_FAILURE = 'FETCH_WINE_REVIEWS_FAILURE';

export const SELECT_WINE_REVIEW = 'SELECT_WINE_REVIEW';